### ISSUE TITLE
Relation with property path translations in entity was not found.

### ISSUE THREAD

**Issue by OlexanderKulyk** [HanMoeHtet/typeorm-translatable#2]
Relation with property path translations in entity was not found.

it's error, I get on simply repository, without TranslatableRepository

**Comment by HanMoeHtet** [comment]
@OlexanderKulyk I think the default `entityManager` from `appDataSource` was overridden which was not the intended behavior. 
For now, just create a new `entityManager` for the repository instead of directly using `appDataSource.entityManger`.


https://github.com/HanMoeHtet/typeorm-translatable#usage-for-repository-extension-experimental
